FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY html/index.html /usr/share/nginx/html/index.html
COPY html/style.css /usr/share/nginx/html/style.css
COPY app.js /usr/share/nginx/html/app.js
EXPOSE 80